#!/bin/bash

# shellcheck disable=SC1091
source "$(dirname "$0")/src/functions/dialog"
source "$(dirname "$0")/src/functions/recode"
source "$(dirname "$0")/src/functions/folders"
source "$(dirname "$0")/src/functions/extract"
source "$(dirname "$0")/src/routes/folderRoutes"
source "$(dirname "$0")/src/locales/getDictionary"
source "$(dirname "$0")/src/locales/getSystemLang"

while getopts ":xyz:" opt; do
  case $opt in
  x) folders ;;
  y) recode ;;
  z) extract ;;
  *) echo "Error: -$OPTARG" >&2 ;;
  esac
done
