#!/bin/bash

RAW_DIR=$*
CURRENT_DIR="${RAW_DIR#*' '}"

function folders() {

  kdialog_name=$(dialog)

  if [ -n "$kdialog_name" ]; then
    mkdir -p "$CURRENT_DIR/$kdialog_name"
    # shellcheck disable=SC2154
    for folder in "${folders[@]}"; do
      mkdir -p "$CURRENT_DIR/$kdialog_name/$folder"
    done
  fi
}
